"""crear models user rol

Revision ID: 335b70c8bd3f
Revises: e2931963753f
Create Date: 2025-04-03 10:29:38.329760

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "335b70c8bd3f"
down_revision: Union[str, None] = "e2931963753f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("estado_audit", sa.Boolean(), nullable=False),
        sa.Column("usuario_creacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=False),
        sa.Column("usuario_modificacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_modificacion", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("module", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=False)
    op.create_index(
        op.f("ix_permissions_estado_audit"), "permissions", ["estado_audit"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("estado_audit", sa.Boolean(), nullable=False),
        sa.Column("usuario_creacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=False),
        sa.Column("usuario_modificacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_modificacion", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("is_system_role", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_estado_audit"), "roles", ["estado_audit"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("estado_audit", sa.Boolean(), nullable=False),
        sa.Column("usuario_creacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=False),
        sa.Column("usuario_modificacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_modificacion", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "LOCKED",
                "PASSWORD_EXPIRED",
                "PENDING_ACTIVATION",
                name="userstatus",
            ),
            nullable=False,
        ),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("password_change_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_estado_audit"), "users", ["estado_audit"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("estado_audit", sa.Boolean(), nullable=False),
        sa.Column("usuario_creacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=False),
        sa.Column("usuario_modificacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_modificacion", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_role_permissions_estado_audit"), "role_permissions", ["estado_audit"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("estado_audit", sa.Boolean(), nullable=False),
        sa.Column("usuario_creacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=False),
        sa.Column("usuario_modificacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_modificacion", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_roles_estado_audit"), "user_roles", ["estado_audit"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_roles_estado_audit"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_role_permissions_estado_audit"), table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_estado_audit"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_estado_audit"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_estado_audit"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_code"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
