"""Initial migration

Revision ID: e2931963753f
Revises:
Create Date: 2025-03-15 23:32:16.616219

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2931963753f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clientes",
        sa.Column("estado_audit", sa.Boolean(), nullable=False),
        sa.Column("usuario_creacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=False),
        sa.Column("usuario_modificacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_modificacion", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("apellidos", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "tipo_documento",
            sa.Enum("CARNET_IDENTIDAD", "PASAPORTE", "OTRO", name="tipodocumento"),
            nullable=False,
        ),
        sa.Column("numero_documento", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("direccion", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("telefono", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("fecha_nacimiento", sa.Date(), nullable=True),
        sa.Column("nacionalidad", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("preferencias", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("estado", sa.Enum("ACTIVO", "INACTIVO", name="estadocliente"), nullable=False),
        sa.Column("fecha_registro", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clientes_estado_audit"), "clientes", ["estado_audit"], unique=False)
    op.create_table(
        "log_auditoria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fecha_hora", sa.DateTime(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("tipo_accion", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("modulo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entidad", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entidad_id", sa.Integer(), nullable=True),
        sa.Column("detalles", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ip_origen", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resultado", sa.Boolean(), nullable=False),
        sa.Column("descripcion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_log_auditoria_entidad"), "log_auditoria", ["entidad"], unique=False)
    op.create_index(
        op.f("ix_log_auditoria_entidad_id"), "log_auditoria", ["entidad_id"], unique=False
    )
    op.create_index(op.f("ix_log_auditoria_modulo"), "log_auditoria", ["modulo"], unique=False)
    op.create_index(
        op.f("ix_log_auditoria_tipo_accion"), "log_auditoria", ["tipo_accion"], unique=False
    )
    op.create_index(
        op.f("ix_log_auditoria_usuario_id"), "log_auditoria", ["usuario_id"], unique=False
    )
    op.create_table(
        "contactos_emergencia",
        sa.Column("estado_audit", sa.Boolean(), nullable=False),
        sa.Column("usuario_creacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=False),
        sa.Column("usuario_modificacion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha_modificacion", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("relacion", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("telefono", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contactos_emergencia_estado_audit"),
        "contactos_emergencia",
        ["estado_audit"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contactos_emergencia_estado_audit"), table_name="contactos_emergencia")
    op.drop_table("contactos_emergencia")
    op.drop_index(op.f("ix_log_auditoria_usuario_id"), table_name="log_auditoria")
    op.drop_index(op.f("ix_log_auditoria_tipo_accion"), table_name="log_auditoria")
    op.drop_index(op.f("ix_log_auditoria_modulo"), table_name="log_auditoria")
    op.drop_index(op.f("ix_log_auditoria_entidad_id"), table_name="log_auditoria")
    op.drop_index(op.f("ix_log_auditoria_entidad"), table_name="log_auditoria")
    op.drop_table("log_auditoria")
    op.drop_index(op.f("ix_clientes_estado_audit"), table_name="clientes")
    op.drop_table("clientes")
    # ### end Alembic commands ###
